name: eslint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: run lint
        run: make lint
